---
# tasks file for awx_post_inventory
- name: POST {{ awx_url }}/api/v2/inventories/
  uri:
    url: "{{ awx_url }}/api/v2/inventories/"
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body:
      name: "test_inventory"
      organization: 1
      kind: ""
    user: "{{ awx_username }}"
    password: "{{ awx_password }}"
    method: POST
  register: post_inventory
  ignore_errors: yes

- debug:
    msg: "{{ post_inventory }}"
