---
# tasks file for awx_post_project
- name: POST {{ awx_url }}/api/v2/projects/
  uri:
    url: "{{ awx_url }}/api/v2/projects/"
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    body:
      name: "test_project"
      local_path: "streisand_test"
    user: "{{ awx_username }}"
    password: "{{ awx_password }}"
    method: POST
  register: post_project
  ignore_errors: yes

- debug:
    msg: "{{ post_project }}"

